name: S3 Upload

on:
  push:
    branches:
      - main

jobs:
  s3_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy files to S3
        run: |
          sudo apt-get update && sudo apt-get install -y s3cmd
          s3cmd --access_key="$ACCESS_KEY" --secret_key="$SECRET_KEY" put index.html style.css reset.css s3://the-cloud-resume-challenge-bucket/
        env:
          ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
