name: S3 Upload

on:
  push:
    branches:
      - main

jobs:
  s3_upload:
    runs-on: ubuntu-latest
    steps:

      - name: Set up S3cmd cli tool
        uses: s3-actions/s3cmd@v1.5.0
        with:
          provider: aws # default is linode
          region: 'eu-central-1'
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Interact with object storage
        run: |
          ls
          s3cmd put ./../style.css --mime-type 'text/css' --acl-public s3://the-cloud-resume-challenge-bucket/style.css
          s3cmd put ./../reset.css --mime-type 'text/css' --acl-public s3://the-cloud-resume-challenge-bucket/reset.css
          s3cmd put ./../index.html --mime-type 'text/html' --acl-public s3://the-cloud-resume-challenge-bucket/index.html
